#!/usr/bin/env bash

function cdpath_maker() {
    unset CDPATH
    CDPATH=".:${HOME}"

    for i in ${@}; do
        CDPATH="${CDPATH}:${i}"
    done
    # remove leading . cause not safe i think
    CDPATH="${CDPATH#.}"
}

## per bpkg guidelines
if [[ ${BASH_SOURCE[0]} != "${0}" ]]; then
    export -f cdpath_maker
    cdpath_maker ~/{Dropbox,Google,OneDrive} ~/Documents/{apache2,{,apache2/www}}
else
    :
fi
