#!/usr/bin/env bash

# Note: only tested on macOS; asssumes appropriate pips installed
# Disclaimer: use at your own peril
# Parting words: have a nice day

shopt -s expand_aliases

export PIP_DISABLE_PIP_VERSION_CHECK=1
# edit this accordingly
pyverz=(
    "2.7"
    "3.4"
    "3.6"
)

for py in "${pyverz[@]}"
do
    if command -v "python${py}" > /dev/null 2>&1
    then
        pyvar="python${py} -m pip"
        opts="--cache-dir=${HOME}/.pip/$py/cache --disable-pip-version-check --user"
        alias py="${pyvar}"

        source <(cat << EOF
function gpip${py//./} ()
{
        if [[ "\$*" =~ "list" ]]
        then
            py "\$*" --format=columns
        elif [[ "\$*" =~ "uninstall" ]]
        then
            ${pyvar} "\$@"
        elif [[ "\$*" =~ install ]]
        then
            ${pyvar} "\$@" $opts
        elif [[ "\$*" =~ "upgrade" ]]
        then
            py freeze | grep -v '^\\-e' | cut -d = -f 1 | xargs -n1 ${pyvar} install -U
        elif [[ "\$*" =~ config|check|search ]]
        then
           py "\$*"
        else
            echo "Unsupported option."
        fi
}
EOF
                )
    fi
done
